serverName='http://localhost:8080'
grails.serverURL='http://localhost:8080/collectory'
security.cas.bypass = true
security.apikey.checkEnabled = false
workDir='/data/dwc-archive/work'
gbifApiUrl='http://api.gbif.org/v1'
uploadFilePath='/data/collectory-plugin/upload'
google.apikey = "PLEASE_SPECIFY_IN_CONFIG_FILE"
institution.codeLoaderURL='file:/data/collectory/bootstrap/institution_codes.xml'
